@startuml
'https://plantuml.com/use-case-diagram
left to right direction


rectangle AccountSystem {
    usecase "Registrate Account" as AS1
    usecase "Delete Account" as AS2
    usecase "Login" as AS3
    usecase "Logout" as AS4
}

NewUser --> AS1
User --> AS2
User --> AS3
User --> AS4


rectangle UserActions {
    usecase "Search Bookmark" as UA1
    usecase "Create Bookmark" as UA2
    usecase "Delete Bookmark" as UA3
    usecase "Edit Bookmark" as UA4
    usecase "Create list(?)" as UA5
}

User --> UA1
User --> UA2
User --> UA3
User --> UA4
User --> UA5


card Backend

AS1 -- Backend
AS2 -- Backend
AS3 -- Backend
AS4 -- Backend

UA1 -- Backend
UA2 -- Backend
UA3 -- Backend
UA4 -- Backend
UA5 -- Backend


@enduml